version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:8080"
    volumes:
      - ./:/var/www/project
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - db
    networks:
      - nginx-php81-mysql8

  web:
    build:
      context: deploy/php
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./:/var/www/project/
      - ./deploy/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - nginx-php81-mysql8

  db:
    image: mysql:8.0.31
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./deploy/mysql/my.cnf:/etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - nginx-php81-mysql8

networks:
  nginx-php81-mysql8: